kotlinx-io-native/src/main/kotlin/kotlinx/io/core/IoBufferNative.kt

so that IoBuffer can be used to read AND write on a memory chunk.

Adds a cpointer constructor to native IoBuffer

---

core/commonMain/src/kotlinx/io/buffer/BufferOperations.kt
core/commonMain/src/kotlinx/io/buffer/PrimitivesOperations.kt
core/commonTest/src/kotlinx/io/tests/Platform.kt
core/commonTest/src/kotlinx/io/tests/buffer/BufferExceptionsTest.kt
core/jsMain/src/kotlinx/io/buffer/JsPrimitivesOperations.kt
core/jsTest/src/kotlinx/io/tests/PlatformJs.kt
core/jvmMain/src/kotlinx/io/buffer/JvmPrimitivesOperations.kt
core/jvmTest/src/kotlinx/io/tests/PlatformJvm.kt
core/nativeMain/src/kotlinx/io/buffer/NativeBufferUtils.kt
core/nativeMain/src/kotlinx/io/buffer/NativePrimitivesOperations.kt
core/nativeTest/src/kotlinx/io/tests/PlatformNative.kt

* Enable long-addressing for bytes
* Get rid of inline because primitive functions are large enough to make a negative impact
* Make slow-paths during unaligned access non-inline for the same reasons

Slightly change buffer primitive operations on Native

---

TODO.md
core/commonMain/src/kotlinx/io/BytesBuilders.kt
core/commonMain/src/kotlinx/io/Input.kt
core/commonMain/src/kotlinx/io/Output.kt
core/jsMain/src/kotlinx/io/Console.kt
core/jvmMain/src/kotlinx/io/Console.kt
core/nativeMain/src/kotlinx/io/Console.kt
playground/jvmMain/src/kotlinx/io/bytes/ByteArrayOutput.kt
playground/jvmMain/src/kotlinx/io/gzip/GzipOutput.kt

* Make Output.close final
* Flush buffered data before closing the underlying source in Output.close because it is the only reasonable behaviour
* Properly handle exceptions during termination sequence

Introduce closeSource method to Output

---

README.md
build.gradle.kts
buildSrc/build.gradle.kts
gradle.properties

Bump up the Kotlin version to 1.8.21, updated README.
There are no obvious reasons to stick to the older Kotlin version.
Also, there was a bug in the multiplatform plugin not allowing to run tests on the WatchOS emulator and it was fixed in 1.8.*.

Bump up Kotlin version to 1.8.21

---

benchmarks/README.md
benchmarks/build.gradle.kts
benchmarks/src/commonMain/kotlin/BufferOps.kt
benchmarks/src/commonMain/kotlin/Constants.kt
benchmarks/src/commonMain/kotlin/PeekBenchmark.kt
benchmarks/src/commonMain/kotlin/SegmentPoolBenchmark.kt
benchmarks/src/jvmMain/kotlin/SegmentPoolBenchmarkMT.kt
build.gradle.kts
gradle.properties
settings.gradle.kts

Added kotlinx-io benchmarks suite.
The suite aimed to track how the performance of the library changes between releases and also to validate the performance on platforms other than JVM.
Currently, only benchmarks covering the very core part of an API were added as that API's part likely won't change in the near future.
The suite doesn't facilitate comparing the performance with other libraries (Okio, ktor-io), but for Okio it could be done by simply replacing import statements in benchmarks from`kotlinx.io` to `okio`, thanks to API's compatibility.

Add benchmarks suite

---

benchmarks/src/commonMain/kotlin/BufferOps.kt
core/api/kotlinx-io-core.api
core/common/src/SinkExt.kt
core/common/src/SourceExt.kt
core/common/src/Utf8.kt
core/common/test/AbstractSinkTest.kt
core/common/test/AbstractSourceTest.kt
core/common/test/CommonBufferTest.kt
core/common/test/CommonPlatformTest.kt
core/common/test/CommonRealSinkTest.kt
core/common/test/CommonRealSourceTest.kt
core/common/test/Utf8Test.kt
core/common/test/files/SmokeFileTest.kt
core/jvm/src/SinkExtJvm.kt
core/jvm/test/AbstractSinkTestJVM.kt
core/jvm/test/AbstractSourceTestJVM.kt
core/jvm/test/BufferTest.kt
core/jvm/test/JvmPlatformTest.kt
core/jvm/test/NioTest.kt

Closes https://github.com/Kotlin/kotlinx-io/issues/155; see the ticket for the rationale.

Rename string read/writeUtf8 methods

---

bytestring/common/src/ByteString.kt
bytestring/common/test/ByteStringTest.kt

Buffer's use lower-case characters, stdlib's `HexFormat` use lower-case characters by default too.
Fixed case of the characters appearing in `ByteString::toString` for consistency.

Use lower case letters for hex-formatted ByteStrings

---

README.md

Updated README w/ information about modules and KMP builds:
- included information about modules
- added badge for KDoc
- described how to add the dependency to KMP project

Updated README w/ information about modules and KMP builds

---

README.md
core/build.gradle.kts

Fixes https://github.com/Kotlin/kotlinx-io/issues/169

Change the type of bytestring module dependency to api

---

CHANGELOG-0.1.X.md
CHANGELOG.md

Fixes https://github.com/Kotlin/kotlinx-io/issues/173

Created new changelog file

---

benchmarks/build.gradle.kts
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
bytestring/build.gradle.kts
core/build.gradle.kts
gradle/libs.versions.toml

Fixes https://github.com/Kotlin/kotlinx-io/issues/180

Use versions catalog to manage dependencies

---

benchmarks/src/commonMain/kotlin/BufferOps.kt
benchmarks/src/commonMain/kotlin/PeekBenchmark.kt

Currently, not all benchmarks could be executed on native targets because only a few of them are explicitly annotated with @State. The majority of benchmarks inherit that annotation from a base class. It works fine w/ JMH, but doesn't work for native targets.
The change will make all benchmarks executable on native targets.

Explicitly annotate all benchmark classes w/ State

---

benchmarks/build.gradle.kts
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-clean.gradle.kts
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-multiplatform.gradle.kts

After upgrading the Gradle, jobs are intermittently failing on Windows with the following error:
```
Execution failed for task ':kotlinx-io-benchmarks:clean'. org.gradle.api.UncheckedIOException: java.io.IOException: Unable to delete directory 'Z:\BuildAgent\work\22e3a7db6b861ba7\benchmarks\build'
Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
- Z:\BuildAgent\work\22e3a7db6b861ba7\benchmarks\build\tmp\.cache\expanded\expanded.lock
- Z:\BuildAgent\work\22e3a7db6b861ba7\benchmarks\build\tmp\.cache\expanded
- Z:\BuildAgent\work\22e3a7db6b861ba7\benchmarks\build\tmp\.cache
- Z:\BuildAgent\work\22e3a7db6b861ba7\benchmarks\build\tmp
```
Picked the workaround from `kotlinx-datetime`: …

Workaround for expanded lock on Windows

---

README.md
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-multiplatform.gradle.kts
bytestring/build.gradle.kts
core/build.gradle.kts
core/native/src/files/PathsNative.kt
core/native/test/util.kt
gradle/libs.versions.toml
kotlin-js-store/yarn.lock

Upgrade kotlin

---

gradle/libs.versions.toml

Upgraded kotlinx-benchmark to a version supporting Kotlin 1.9.0.
Didn't enable native benchmarks by default because issue with stability is still there.

Bump up kotlinx-benchmark version

---

core/api/kotlinx-io-core.api
core/common/src/Buffer.kt
core/common/src/Buffers.kt
core/common/src/Segment.kt
core/common/src/Sources.kt

Improved performance of `Source.indexOf`.
Tests execution time in CI halved.
Closes #162

Speedup indexof

---

core/api/kotlinx-io-core.api
core/common/src/Sinks.kt
core/common/src/Sources.kt
core/common/test/AbstractSinkTest.kt
core/common/test/AbstractSourceTest.kt
core/common/test/samples/samples.kt

Implemented extension functions for reading and writing values with types Float and Double
Resolves #167

Added API for reading and writing of floating point numbers

---

benchmarks/src/commonMain/kotlin/BufferOps.kt
benchmarks/src/commonMain/kotlin/bytestring/ByteStringOps.kt

Added benchmarks covering the following functions:
- indexOf
- lastIndexOf
- startsWith
- endsWith
- hashCode
- compareTo
Fixes #153

Added ByteString benchmarks

---

bytestring/common/src/-Platform.kt
bytestring/common/src/ByteString.kt
bytestring/native/src/-PlatformNative.kt

It has a benign JVM data-race on the hashCode field, but on K/N LLVM has no guarantees it will read default or written value (e.g. OoTA is one of the possibilities). The recommendation from K/N folks is to use @Volatile here
Fixes #190

Fix potential UB in ByteString.hashCode

---

README.md
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-multiplatform.gradle.kts
core/build.gradle.kts
core/wasm/src/-PlatformWasm.kt
core/wasm/src/RawSink.kt
core/wasm/src/SegmentPool.kt
core/wasm/src/files/PathsWasm.kt
core/wasm/test/utils.kt
gradle/libs.versions.toml
kotlin-js-store/yarn.lock

Enabled Wasm target and updated Kotlin to 1.9.10. The latter is required due to a bug in Wasm backend in 1.9.0

Wasm target support

---

README.md

Just some minor cleanup of the front-facing documentation.

Rework the readme overview section to be more fluent

---

core/android/src/files/FileSystemAndroid.kt
core/apple/src/files/FileSystemApple.kt
core/common/test/files/SmokeFileTest.kt
core/linux/src/files/FileSystemLinux.kt
core/mingw/src/files/FileSystemMingw.kt
core/mingw/test/files/SmokeFileTestWindows.kt
core/native/src/files/PathsNative.kt

Previously, shared native `Path.parent` implementation could filter out a windows path using `\` as a separator. 
This behavior was fixed to correctly process paths using both `\` and `/` on Windows.
Fixes #221

Correctly extract parent path on Windows

---

core/api/kotlinx-io-core.api
core/apple/src/files/FileSystemApple.kt
core/common/src/files/FileSystem.kt
core/common/test/files/SmokeFileTest.kt
core/js/src/files/FileSystemJs.kt
core/jvm/src/files/FileSystemJvm.kt
core/mingw/src/files/FileSystemMingw.kt
core/native/src/files/FileSystemNative.kt
core/unix/src/files/FileSystemUnix.kt
core/wasm/src/files/FileSystemWasm.kt

Support path resolution

---

build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-multiplatform.gradle.kts
core/build.gradle.kts

Added WasmWasi target sharing the same source code with WasmJs target for now.
Closes #234

Enable WasmWasi target

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-dokka.gradle.kts
bytestring/build.gradle.kts
core/build.gradle.kts
gradle/libs.versions.toml

For context: https://github.com/Kotlin/kotlinx.coroutines/issues/3929 and https://github.com/Kotlin/kotlinx.coroutines/pull/3960

Update Gradle Dokka configuration to make sure "source" button is visible in all API docs

---

build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-dokka.gradle.kts

Based on discussion: https://github.com/Kotlin/kotlinx-datetime/pull/323#discussion_r1412147614
Checked locally - content is identical for both approaches

Simplify Dokka source link configuration

---

build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-multiplatform.gradle.kts

There's absolutely no sense in building executable Wasm and Js binaries as `kotlinx-io` is a library and not supposed to be executed on its own.
Kudos to @lppedd for spotting the issue.

Don't build JS and Wasm executable files

---

core/common/test/files/SmokeFileTest.kt
core/js/src/files/PathsJs.kt

For JS, unlike other targets, a file was not opened on file sink/source creation. 
For a sink, it was leading to different behavior when the sink was closed without a single byte written to it: on all targets except JS an empty file is created.
For a source, on all targets except JS, an attempt to create a source for a non-existent file is immediately reported as an error, but for JS the error won't be reported until an actual read operation is employed.
This PR aligns JS target's behavior will all other targets.
Fixes #251

Align file sink and source creation behavior across targets

---

benchmarks/build.gradle.kts

Current build script will no longer work with K2.

Correctly setup toolchain in benchmarks module

---

gradle/libs.versions.toml

No issues found comparing to 1.9.10

Update Dokka to 1.9.20

---

.idea/vcs.xml

Highlights and links to GH issues:
Longer description to not repeat: https://github.com/Kotlin/dokka/pull/3341
(not sure though about the target branch: master vs develop)

Enable issue navigation

---

core/common/src/-CommonPlatform.kt
core/js/src/-PlatformJs.kt
core/native/src/-NonJvmPlatform.kt
core/wasm/src/-PlatformWasm.kt

Overload IOException constructor

---

core/js/src/node/nodeModulesJs.kt

Trick the webpack to bypass its warnings on missing modules

---

core/apple/src/files/FileSystemApple.kt
core/native/src/files/FileSystemNative.kt
core/nonApple/src/files/FileSystemNonApple.kt

Starting from May 1, 2024 developers have to explicitly declare why they use APIs allowing to access file timestamps in privacy manifest files; otherwise, an app won't be accepted by the AppStore. 
The only restricted API we're currently using is stat, and since we don't extract any timestamps using it, we can safely replace it with NSFileManager::fileAttributesAtPath.
For more details on the restriction imposed on timestamp-accessing APIs read https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
Closes #297

Replace stat call with NSFileManager API on Apple target

---

core/common/src/-CommonPlatform.kt
core/common/src/Sinks.kt
core/common/src/internal/-Utf8.kt
core/common/test/AbstractSourceTest.kt
core/common/test/Utf8Test.kt
core/common/test/util.kt
core/js/src/-PlatformJs.kt
core/js/test/utils.kt
core/jvm/src/-JvmPlatform.kt
core/jvm/test/utilJVM.kt
core/native/src/-NonJvmPlatform.kt
core/native/test/util.kt
core/wasm/src/-PlatformWasm.kt
core/wasm/test/utils.kt

Added tests to cover some UTF-8-related edge cases and moved functions used primarily by tests to corresponding source sets.

Improve test coverage

---

core/common/src/Utf8.kt

Follow up to https://github.com/Kotlin/kotlinx-io/pull/308

Improve writeCodePointValue KDoc

---

core/common/src/Utf8.kt
core/common/test/Utf8Test.kt

Correctly handle negative code point values

---

build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-dokka.gradle.kts
bytestring/build.gradle.kts
core/build.gradle.kts

Fixes #210
Note: I've also moved `unsafe` package hiding to convention plugin, because AFAIU the same idea of not advertising of this API in official documentation will be applied to `unsafe` APIs in `core`.

Move samples and packages configuration of Dokka to convention plugin

---

core/common/src/Sinks.kt
core/common/src/Sources.kt

Addresses concerns described in #322

Clarify writeFloat/readFloat behavior on Kotlin/JS

---

core/api/kotlinx-io-core.api
core/api/kotlinx-io-core.klib.api
core/common/src/Utf8.kt
core/common/test/AbstractSinkTest.kt
core/common/test/Utf8Test.kt
core/common/test/samples/samples.kt

Add Sink.writeString(CharSequence)

---

core/common/src/-Util.kt
core/common/src/Sinks.kt
core/common/test/UtilsTest.kt

While preparing #337, I noticed that the way the length of the number to be encoded into a hexadecimal string could be significantly simplified. As a bonus, the clz-based version also works faster.
Moved the logic into a separate function to cover it with explicit tests.

Simplify evaluation of hex-encoded number's length

---

core/common/src/Utf8.kt

Improves `readCodePointValue` performance by ~10% when the receiver is `Buffer`.
Addresses a particular issue uncovered in https://github.com/Kotlin/kotlinx.serialization/pull/2707.
In general, similar issues will be tracked by https://github.com/Kotlin/kotlinx-io/issues/342.
Benchmarking results w/ jdk21 on macOS host w/ AS M2 Pro CPU:
- before:
```
Benchmark                                                (encoding)  (minGap)   Mode  Cnt          Score         Error  Units
Utf8CodePointsBenchmark.benchmark                             ascii       128  thrpt    5  140373273.339 ±  694216.983  ops/s
Utf8CodePointsBenchmark.benchmark                              utf8       128  thrpt    5   87815553.220 ± 1128003.103  ops/s
Utf8CodePointsBenchmark.benchmark                            sparse …
```

Avoid unnecessary checks when calling readCodePointValue on Buffer

---

core/apple/src/AppleCore.kt
core/apple/src/BuffersApple.kt
core/common/src/Buffer.kt
core/common/src/Buffers.kt
core/common/src/ByteStrings.kt
core/common/src/Segment.kt
core/common/src/Utf8.kt
core/common/test/util.kt
core/jvm/src/BuffersJvm.kt
core/jvm/src/JvmCore.kt
core/jvm/src/SourcesJvm.kt

Previously, Buffer's segments were organized into a circular list. 
That allowed storing only a single reference to buffer's head, and also facilitated insertion/removal of new list nodes.
The downside of a circular list is that one has to always compare a current node with a head when iterating over segments.
That complicates the implementation of a public API for segments iterations (See https://github.com/Kotlin/kotlinx-io/issues/135#issuecomment-2125014081 for details on segment iteration API).
This PR changes how segments are organized within a buffer to no longer form a circular list. Head's previous node and tail's next node now will always be `null`.

[PR 1/5] Organize Buffer's segments as a regular list

---

core/common/src/Buffer.kt
core/common/test/CommonBufferTest.kt

Buffer's head/tail update after the split was incorrect (I'm not sure what I was thinking about when I changed it).
It does not matter how many segments a buffer has, the split affects only a head one, so tail reference remains valid no matter what; thus only a head needs to be updated.

Correctly split head segment

---

benchmarks/build.gradle.kts
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-dokka.gradle.kts
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-multiplatform.gradle.kts
build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-publish.gradle.kts

https://blog.gradle.org/simpler-kotlin-dsl-property-assignment

Simple property assignments and dropping Property by extension

---

bytestring/common/src/unsafe/UnsafeByteStringOperations.kt
bytestring/common/test/unsafe/UnsafeByteStringOperationsTest.kt
core/common/src/Buffer.kt
core/common/src/Sinks.kt
core/common/src/unsafe/UnsafeBufferOperations.kt
core/common/test/DelicateApiTest.kt
core/common/test/unsafe/UnsafeBufferOperationsIterationTest.kt
core/common/test/unsafe/UnsafeBufferOperationsReadTest.kt
core/common/test/unsafe/UnsafeBufferOperationsWriteTest.kt
core/jvm/src/unsafe/UnsafeBufferOperationsJvm.kt
core/jvm/test/unsafe/UnsafeBufferOperationsJvmReadBulkTest.kt
core/jvm/test/unsafe/UnsafeBufferOperationsJvmReadFromHeadTest.kt
core/jvm/test/unsafe/UnsafeBufferOperationsJvmWriteToTailTest.kt

Add calls-in-place contracts to unsafe operations

---

core/common/src/ByteStrings.kt
core/common/src/RawSink.kt
core/common/src/RawSource.kt
core/common/src/Sink.kt
core/common/src/Sinks.kt
core/common/src/Source.kt
core/common/src/Sources.kt
core/common/src/Utf8.kt
core/jvm/src/SinksJvm.kt
core/jvm/src/SourcesJvm.kt

Previously, it was unclear how `RawSink`/`RawSource` implementations should behave when I/O errors occur.
This PR adds explicit `IOException` mentions to `@throws` lists of these interfaces and also propagates it to all functions that are transitively affected.
Closes #302

Specify IOException among other exception that could be thrown by I/O function calls

---

core/apple/src/AppleCore.kt
core/apple/src/BuffersApple.kt
core/common/src/Buffer.kt
core/common/src/Buffers.kt
core/common/src/ByteStrings.kt
core/common/src/Sinks.kt
core/common/src/Sources.kt
core/common/src/Utf8.kt
core/common/src/unsafe/UnsafeBufferOperations.kt
core/jvm/src/BuffersJvm.kt
core/jvm/src/JvmCore.kt
core/jvm/src/SourcesJvm.kt
core/nodeFilesystemShared/src/files/PathsNodeJs.kt
core/wasmWasi/src/-WasmUtils.kt

This PR reimplements existing extensions to use unsafe API introduced in #334 and #336.
In the next patch, Segment's `data` field will be encapsulated.
Related to #135

[PR 4/5] Rewrite existing extensions using unsafe API

---

benchmarks/README.md
benchmarks/src/commonMain/kotlin/ReadStringBenchmark.kt
core/common/src/Utf8.kt

* Request Long.MAX_VALUE from the source at once (note: no need for a loop as we are unable to build the string of such size anyway)
* Get rid of redundant checks in commonReadUtf8
Ticks one of the boxes in #342

Minor cleanup and simplification of readString

---

core/common/test/samples/byteStringSample.kt
core/common/test/samples/moduleDescriptionSample.kt
core/common/test/samples/rawSinkSample.kt
core/common/test/samples/rawSourceSample.kt
core/common/test/samples/unsafe/unsafeSamples.kt
core/jvm/test/samples/samplesJvm.kt
core/jvm/test/samples/unsafeAccessSamplesJvm.kt

- fixed imports to avoid explicit kotlin.test.Test import
- removed all internal function uses from samples

Update samples that do not work in Playground

---

bytestring/api/kotlinx-io-bytestring.api
bytestring/jvm/src/ByteStringJvmExt.kt
bytestring/jvm/test/ByteStringByteBufferExtensions.kt
bytestring/jvm/test/ByteStringByteBufferExtensionsTest.kt
bytestring/jvm/test/samples/samplesJvm.kt

Read/write ByteString from/to ByteBuffer

---

core/common/src/Segment.kt
core/jvm/src/SegmentPool.kt
core/jvm/test/PoolingTest.kt

Improve segment pool test coverage

---

bytestring/api/kotlinx-io-bytestring.klib.api
bytestring/apple/src/ByteStringApple.kt
bytestring/apple/test/ByteStringAppleTest.kt
bytestring/apple/test/samples/samplesApple.kt

Open questions:
`fun ByteString.toNSData(fromIndex: Int = 0, toIndex = length)`
Closes #266

Support ByteString to/from NSData conversions

---

core/Module.md
core/common/src/Buffer.kt
core/common/src/RawSink.kt
core/common/src/RawSource.kt
core/common/src/Sink.kt
core/common/src/Source.kt
core/common/src/files/FileSystem.kt

Explicitly documents thread-safety guarantees, PeekSource behavior and FileSystem support for JS-target.
Closes #392, #393, #394

Improve documentation

---

core/common/src/Buffer.kt

During implementation for support of `kotlinx-io` in `cryptography-kotlin` at one point I've started to receive the error about `unexpected capacity`, but it was not really informative. The reason for this was, that I haven't handled the case with output of zero size [here](https://github.com/whyoleg/cryptography-kotlin/blob/639b142aa447d882f9c0361b6d7368423c21c47c/cryptography-providers/base/src/commonMain/kotlin/operations/BaseCipherFunction.kt#L128-L141).
It would be nice to have the error message more clear on what's wrong, when using `UnsafeBufferOperations.writeToTail`

Update error message in `writableSegment`

---

core/api/kotlinx-io-core.api
core/common/src/Segment.kt

Publish Segment.size and Segment.remainingCapacity

---

core/common/src/-Util.kt
core/js/src/UtilsJs.kt
core/jvm/src/-UtilsJvm.kt
core/native/src/UtilsNative.kt
core/wasm/src/UtilsWasm.kt

Seems like JVM's JIT compiler can't pattern match bytes reversal, so it's worth explicitly delegating to Java Stdlib functions, that are intrinsics candidates.
For long values, the new implementation shows 20% perf improvement for reversal itself.
Functions depending on it, like readXXXLe or writeXXXLe also show some moderate performance improvement from the change:
- baseline (develop):
```
Benchmark                   (minGap)   Mode  Cnt          Score          Error  Units
IntLeBenchmark.benchmark         128  thrpt   15  387643797.206 ± 13843848.182  ops/s
LongLeBenchmark.benchmark        128  thrpt   15  314485977.158 ±  2249441.675  ops/s
ShortLeBenchmark.benchmark       128  thrpt   15  433907914.224 ±  6445437.883  ops/s
```
- optimized (this PR):
```
Benchmark …
```

Delegate Int|Short|Long.reverseBytes to Java Stdlib

---

smoke-tests/src/test/resources/templates/jvm.build.gradle.kts
smoke-tests/src/test/resources/templates/kmp.build.gradle.kts
smoke-tests/src/test/resources/templates/settings.gradle.kts

By using lowest supported JVM toolchain (8), we should be able to catch an unintentional class file version change.

Fix JVM toolchain version for smoke tests

---

core/androidNative/src/files/FileSystemAndroid.kt
core/native/src/files/PathsNative.kt
core/nativeNonAndroid/src/files/FileSystemNativeNonAndroid.kt
core/wasmWasi/src/files/FileSystemWasm.kt

Check error codes returned by POSIX-ish APIs and throw IOE

---

core/common/src/ByteStrings.kt
core/common/test/AbstractSourceTest.kt
core/common/test/CommonBufferTest.kt
core/jvm/test/BufferTest.kt

Refine Source|Buffer.indexOf(ByteBuffer) contracts

---

build-logic/src/main/kotlin/kotlinx/io/conventions/kotlinx-io-publish.gradle.kts

This replaces the custom name with an SPDX identifier to enable tooling to automatically detect the correct license. Using an SPDX identifier is recommended [by the official Maven documentation](https://maven.apache.org/pom.html#Licenses).
See https://spdx.org/licenses/Apache-2.0.html

Use SPDX identifier in POMs

---

integration/kotlinx-io-okio/common/src/OkioAdapters.kt
integration/kotlinx-io-okio/common/test/OkioAdaptersTest.kt

When byteCount > okio segment size

Fix ArrayIndexOutOfBoundsException in okio.Sink.asKotlinxIoRawSink

---

core/common/src/files/Paths.kt

These functions were deprecated with warning for a while. Their removal was postponed from release to
release, and it's time to at least increase the deprecation level to error.

Increase deprecation level for Path.source/sink
